### ISSUE TITLE
mayukh checklist

### ISSUE THREAD

**Issue by cca4522** [cca4522/project2#1]
# Learning Topics Checklist

- [x] Python Basics
- [x] Variables and Data Types
- [ ] Control Structures (if, for, while)
- [ ] Functions and Modules
- [ ] Object-Oriented Programming (OOP)
- [ ] CLI Tools with sys.argv
- [ ] Virtual Environments
- [ ] Git Basics
- [ ] Working with JSON Files
